### ISSUE TITLE
Some functional question

### ISSUE THREAD

**Issue by JacksonWuxs** [hugovk/pypistats#72]
When I wrote the code as `pypistats overall pandas`,  is that means the number of downloading pandas from PyPi in the history?

**Comment by JacksonWuxs** [comment]
That is because, when I do a test, the number seems unchanged.
![image](https://user-images.githubusercontent.com/28649392/63957507-174b0b80-cabb-11e9-9a58-3a1379f2414e.png)

**Comment by hugovk** [comment]
I'm not entirely sure, it's what is returned by the https://pypistats.org/api/#api-packages-package-overall endpoint. I believe it's for a six-month period, up until yesterday.

A quick check of another endpoint which shows daily downloads (`/python_minor`) returns downloads for 2019-03-01 until 2019-08-28, which is just under 6 months.

@crflynn, please could you confirm the logic? Thank you!

**Comment by crflynn** [comment]
Based on the screenshot, @JacksonWuxs is asking why the counts aren't updating in realtime.

Data comes from pypistats.org, which updates once each day (1AM UTC), since the intent is to aggregate and display download trends with daily granularity. It's not updated in realtime.

pypistats.org data comes from pypi's BigQuery downloads tables, which pypi's infrastructure streams records into. If you want near real-time download stats, use the BigQuery table.

**Comment by hugovk** [comment]
Thanks!

The CLI adds up the daily downloads, I should update it to also print out the time period for those.

**Comment by JacksonWuxs** [comment]
Well, infact I have used the BigQuery table with Google. However, I am not sure about the result from both BigQuery and this project because, I am diffident to say my project can attract such amount of download. Is there any other ways to check this number?

**Comment by crflynn** [comment]
The `without_mirrors` counts are more representative of end-user downloads, and in fact segmentations of other download counts on pypistats exclude certain known mirrors by default. However, the mirror filtration is not exhaustive and there are likely other mirrored downloads not being filtered.

There is also no easy way to filter downloads which are part of automated CI/CD pipelines. These use cases will also inflate download counts.

Because of the way downloads are recorded in general, the counts may not accurately represent end-user implementations of the software. The data should be used -- at best -- as a general baseline for usability by the community, and I would not consider it's accuracy to be robust.

Based on the existence of mirrors, generally one can expect less popular packages to have overestimated download counts, and more popular packages like `numpy` to have underestimated counts.

**Comment by JacksonWuxs** [comment]
Your discussion about the number from those sources seems reasonable. I appreciate your answer.
